config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/whatis'
  get 'static_pages/learners'
  get 'static_pages/teachers'
  get 'static_pages/organizers'
  get 'static_pages/contributors'
  get 'static_pages/media'

  root :to => 'groups#index'

  resources :users do
    resources :skills, only: [:new, :create, :destroy]
  end

  post 'users/:id/enable_facilitator', to: 'users#enable_facilitator', as: 'enable_facilitator'
  post 'users/:id/disable_facilitator', to: 'users#disable_facilitator', as: 'disable_facilitator'

  resource :login

  resources :groups do
    resources :events, only: [:create, :new, :edit, :update, :destroy, :show]
  end

  post 'groups/:group_id/events/:id/attend', to: 'events#attend', as: 'attend_event'
  post 'groups/:group_id/events/:id/unattend', to: 'events#unattend', as: 'unattend_event'

  post 'groups/:group_id/events/:id/agenda', to: 'events#agenda', as: 'create_agenda'

  get 'groups/:group_id/events/:id/visitors', to: 'events#visitors', as: "event_visitors"

  resources :locations, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

  after_initialize :init

  belongs_to :facilitator, { :foreign_key => 'facilitator_id',
    :class_name => 'User'}

  belongs_to :location

  has_many :events, dependent: :destroy

  validates :name, presence: true, length: {minimum: 7, maximum: 50}

  validates :name, uniqueness: { scope: :location_id,
    message: "only one event with this name at your location"}

  validates :max_places, presence: true, numericality:
    {greater_than_or_equal_to: 0, only_integer: true}

  validates :description, length: { maximum: 1000 }

  validates :facilitator_id, presence: true, numericality:
    {greater_than_or_equal_to: 0, only_integer: true}

  validates :area_size, presence: true, numericality:
    {greater_than_or_equal_to: 2, only_integer: true}

  validates :area_count, presence: true, numericality:
    {greater_than_or_equal_to: 1, only_integer: true}

  def build_location
    deftLoc = Location.where(name: "Default").first
    if deftLoc
      return deftLoc
    else
      return Location.create!(name: "Default", country: "Default",
        postnr: 100, city: "Default", street: "Default", number: "Default")
    end
  end

  def init
    self.location ||= build_location
  end

end#class Group

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :correct_facilitator, only: [:edit, :destroy]

  helper_method [:correct_facilitator?, :attending?]

  def new
    if current_user && current_user.facilitator?
      @group = Group.new
      @location = @group.location
    else
      redirect_to root_url
    end
  end

  def create
    if current_user && current_user.facilitator?
      @location = Location.find_or_create_by(group_params[:location])
      @group = current_user.groups.build(group_params.except(:location))

      if @location.valid?
        @group.location = @location
        if @group.valid?
          @group.save
          flash[:success] = "Meeting group created successfully"
          redirect_to root_url
        else
          flash[:danger] = "Meeting group not created"
          render 'new'
        end
      else
        flash[:danger] = "Meeting group not created, invalid location"
        render 'new'
      end
    else
      redirect_to root_url
    end
  end#create

  def show
    @group = Group.find(params[:id])
  end

  def index
    @groups_hash = {}
    if current_user && current_user.facilitator?
      locationsGroups = Location.joins("INNER JOIN groups ON groups.location_id = locations.id AND groups.facilitator_id = #{current_user.id}").distinct.order("country ASC, city ASC")
    else
      locationsGroups = Location.joins("INNER JOIN groups ON groups.location_id = locations.id").
        distinct.order("country ASC, city ASC")
    end
    locationsGroups.each do |loc|
      if @groups_hash[loc.country].nil?
        @groups_hash[loc.country] = {}
      end
      if @groups_hash[loc.country][loc.city].nil?
        @groups_hash[loc.country][loc.city] = []
      end
      loc.groups.each do |grp|
        if current_user && current_user.facilitator?
          if grp.facilitator_id == current_user.id
            @groups_hash[loc.country][loc.city] << grp
          end
        else
          @groups_hash[loc.country][loc.city] << grp
        end
      end

    end
  end #index

  def edit
    if current_user && current_user.facilitator?
      @group = Group.find(params[:id])
      @location = @group.location
    end
  end

  def update
    if current_user && current_user.facilitator?
      @group = Group.find(params[:id])
      if @group && (@group.facilitator_id == current_user.id)
        @location = Location.find_or_create_by(group_params[:location])
        if @location
          @group.location = @location
          @group.save
        end
        @group = Group.update(@group.id, group_params.except(:location))

        if @group && @group.valid? && @location && @location.valid?
          flash[:success] = "Meeting Group Updated"
          redirect_to group_path(@group)
        else
          flash.now[:danger] = "Meeting Group Not Updated"
          render 'edit'
        end
      else
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end

  def destroy
    @group.destroy
    flash[:success] = "Meeting group deleted"
    redirect_to groups_path
  end

  private

    def group_params
      params.require(:group).permit(:name, :max_places,
        :description, :area_size, :area_count, location: [:name,
          :country, :postnr, :city, :street, :number])
    end

end#class GroupsController

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, "Group name" %>
  <%= f.text_field :name %> <br />
  <%= f.label :max_places, "Maximum number of places" %>
  <%= f.number_field :max_places %> <br />
  <%= f.label :description %>
  <%= f.text_area :description %> <br />
  <%= f.label :area_size, "Size of each learning area" %>
  <%= f.number_field :area_size %> <br />
  <%= f.label :area_count, "Number of learning areas" %>
  <%= f.number_field :area_count %> <br />

  <%= f.fields_for @location do |lf| %>
  	<%= lf.label :name, "Location name" %>
  	<%= lf.text_field :name, data: { autocomplete_source: locations_path } %>
  	<%= lf.label :street %>
  	<%= lf.text_field :street %>
  	<%= lf.label :number, "Number" %>
  	<%= lf.text_field :number %>
  	<%= lf.label :city %>
  	<%= lf.text_field :city %>
  	<%= lf.label :postnr, "Postal code" %>
  	<%= lf.text_field :postnr %>
  	<%= lf.label :country %>
  	<%= lf.text_field :country %>
  <% end %>
  <%= f.submit %>

<% end %>

app/views/groups/edit.html.erb
<% provide :page_title, "Edit Meeting Group" %>

<h1> Edit Group </h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<% provide(:page_title, "Learning Groups") %>

<h3>Collaborative Learning in:</h3>

<% if logged_in? && current_user.facilitator? %>
  <div data-role="controlgroup" data-type="horizontal">
    <%= link_to "New Group", new_group_path, "data-role": "button" %>
  </div>
<% end %>

<ul data-role="listview" data-inset="true" data-shadow="false" class="overfill-list">
  <% @groups_hash.each_key do |ctry| %>
    <li data-role="collapsible" data-iconpos="left" data-inset="false">
      <h2> <%= ctry %> </h2>
      <ul data-role="listview" data-theme="d" data-inset="true" data-shadow="false">
        <% @groups_hash[ctry].each_key do |city| %>
          <li data-role="collapsible" data-iconpos="left" data-inset="false">
            <h2> <%= city %> </h2>
            <ul data-role="listview" data-inset="true" data-shadow="false">
            <% @groups_hash[ctry][city].each do |grp| %>
              <li data-theme="b">
                <%= link_to "#{grp.name}", group_path(grp) %>
              </li>
            <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<h1> New Meeting Group </h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<% provide :page_title, "Meeting Group Page" %>

<div class="group-details">

  <ul data-role="listview" data-theme="b" data-inset="true" data-shadow="false" class="overfill-list">
    <li data-role="collapsible" data-iconpos="left" data-inset="false">
      <h2> <%= @group.name %> </h2>
      <ul data-role="listview" data-inset="true" data-shadow="false">
        <li>
          <p class="wrap"><%= @group.description %> </p>
        </li>
      </ul>
    </li>
  </ul>

  <% if correct_facilitator?(@group) %>
    <div class="command-toolbar">
      <div data-role="controlgroup" data-type="horizontal" data-mini="true">
          <%= link_to "Edit", edit_group_path(@group), "data-role": "button",
            class: "ui-btn ui-corner-all ui-btn-icon-left" %>
          <%= form_tag group_path, method: 'delete' do %>
            <%= submit_tag "Delete", data: { confirm: "Are you sure?" } %>
          <% end %>
          <%= link_to "New Event", new_group_event_path(@group), "data-role": "button",
            class: "ui-btn ui-corner-all ui-btn-icon-right" %>
      </div>
    </div>
  <% end %>

  <p>
    <%= @group.location.name %>,
    <%= @group.location.street %>,
    <%= @group.location.number %>,
    <%= @group.location.postnr %>,
    <%= @group.location.city %>,
    <%= @group.location.country %>
  </p>

  <p> Maximum Places: <%= @group.max_places %> </p>
  <% if current_user && current_user.facilitator? %>
    <p> Area Size: <%= @group.area_size %> </p>
    <p> Area Count: <%= @group.area_count %> </p>
  <% end %>

  <% if !logged_in? %>
    <%= link_to "Sign in", new_login_path, "data-role": "button", "data-theme": "c" %>
  <% end %>
</div>

<h3>Events</h3>
<table data-role="table" id="event-table" data-mode="reflow" class="ui-responsive events">
  <thead>
    <tr>
      <th> Date </th>
      <th> Start </th>
      <th> End </th>
      <th> Places Left </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @group.events.order(:time_start).each do |event| %>
      <tr id="<%= event.id %>" >
      <%= render event, object: event %>
      </tr>
    <% end %>
  </tbody>
</table>