config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/whatis'
  get 'static_pages/learners'
  get 'static_pages/teachers'
  get 'static_pages/organizers'
  get 'static_pages/contributors'
  get 'static_pages/media'

  root :to => 'groups#index'

  resources :users do
    resources :skills, only: [:new, :create, :destroy]
  end

  post 'users/:id/enable_facilitator', to: 'users#enable_facilitator', as: 'enable_facilitator'
  post 'users/:id/disable_facilitator', to: 'users#disable_facilitator', as: 'disable_facilitator'

  resource :login

  resources :groups do
    resources :events, only: [:create, :new, :edit, :update, :destroy, :show]
  end

  post 'groups/:group_id/events/:id/attend', to: 'events#attend', as: 'attend_event'
  post 'groups/:group_id/events/:id/unattend', to: 'events#unattend', as: 'unattend_event'

  post 'groups/:group_id/events/:id/agenda', to: 'events#agenda', as: 'create_agenda'

  get 'groups/:group_id/events/:id/visitors', to: 'events#visitors', as: "event_visitors"

  resources :locations, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :groups, { :foreign_key => 'facilitator_id' }

  has_and_belongs_to_many :events

  has_many :skills

  validates :name, presence: true, length: {minimum: 4, maximum: 30}
  validates :password, presence: true, length: {minimum: 5, maximum: 30}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i

  validates :email, format: {with: VALID_EMAIL_REGEX,
      message: "address is not valid"}, length: {maximum: 50},
      uniqueness: true

  ROLE = {:VISITOR => 1, :FACILITATOR => 2, :ADMIN => 3, :BANNED => 0 }
  ROLE_STR = {:VISITOR => "Visitor", :FACILITATOR => "Facilitator",
    :ADMIN => "Admin"}

  def User.authenticate(emailStr, pwdStr)
    user = User.find_by(email: emailStr, password: pwdStr)
  end

  # Returns role code from the array of role symbols
  def User.roles(roleSyms)
    val = 0
    for roleSym in roleSyms
      val |= 2 ** ROLE[roleSym]
    end
    return val
  end

  def role_str
    if admin?
      return ROLE_STR[:ADMIN]
    elsif facilitator?
      return ROLE_STR[:FACILITATOR]
    elsif visitor?
      return ROLE_STR[:VISITOR]
    end
  end

  def admin?
    ((role >> ROLE[:ADMIN]) & 1) == 1
  end

  def facilitator?
    ((role >> ROLE[:FACILITATOR]) & 1) == 1
  end

  def visitor?
    ((role >> ROLE[:VISITOR]) & 1) == 1
  end

  def make_facilitator
    self.role |= (2 ** ROLE[:FACILITATOR])
  end

  def unmake_facilitator
    self.role &= ~(2**ROLE[:FACILITATOR])
  end

  def banned?
    ((role >> ROLE[:BANNED]) & 1) == 1
  end

  def learns(knowhow)
    self.skills.create(knowhow_id: knowhow.id)
  end

  def learns_by_id(knowhow_id)
    self.skills.create(knowhow_id: knowhow_id)
  end

  def teaches(knowhow)
    self.skills.create(knowhow_id: knowhow.id, teaching: true)
  end

  def teaches_by_id(knowhow_id)
    self.skills.create(knowhow_id: knowhow_id, teaching: true)
  end

end#User

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if current_user.nil?
      @user = User.new
    else
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)
    ###if verify_recaptcha(model: @user) && @user.save
    if @user.save      
      set_current_user(@user)
      msg = @user.name.split()[0] + ", please add some skills to your profile."
      flash[:success] = msg
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = 'Please correct your registration data'
      render 'new'
    end
  end

  def show
    if (params[:id].to_i == session[:current_user_id]) ||
      (current_user && current_user.admin?)
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if (current_user != @user) && (! current_user.admin?)
      redirect_to root_url
    end
  end

  def update
    if current_user
      stt = current_user.update(user_params)
      if stt
        flash[:success] = "Profile update successful"
        redirect_to root_url
      else
        flash[:danger] = "Profile update failed"
        render 'edit'
      end
    end
  end

  def index
    if current_user && current_user.admin?
      @users = User.all
    else
      redirect_to root_url
    end
  end

  def enable_facilitator
    @user = User.find(params[:id])
    if current_user.admin? && @user.visitor?
      @user.make_facilitator
      @user.save
      redirect_to user_path(@user)
    else
      render 'show'
    end
  end

  def disable_facilitator
    @user = User.find(params[:id])
    if current_user.admin? && @user.facilitator?
      @user.unmake_facilitator
      @user.save
      redirect_to user_path(@user)
    else
      render 'show'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %> <br />
  </div>
  <div>
  <%= f.label :email %>
  <%= f.text_field :email %> <br />
  </div>
  <div>
  <%= f.label :password %>
  <%= f.password_field :password %> <br />
  </div>  
  <%### recaptcha_tags %>

  <div>
  <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:page_title, "Edit Profile") %>

<h1> Edit Profile </h2>

  <%# form_for(current_user, url: user_path()) do |f| %>

  <%# form_for(current_user) do |f| %>
  <%= form_for(@user) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br />
    <%= f.label :email %>
    <%= f.text_field :email %> <br />
    <%= f.label :password %>
    <%= f.password_field :password %> <br />
    <%= f.submit %>
  <% end %>

<%= link_to "Home", root_url %>

app/views/users/index.html.erb
<h1> Users Index </h1>
<% if @users %>
  <ul>
  <% for user in @users %>
    <li> <%= link_to user.name, user_path(user) %>  </li>
  <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<% provide(:page_title, "Sign up") %>

<h1>Please sign up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h2> User Profile </h2>

<table data-role="table" data-mode="reflow" class="ui-responsive table-stroke">
  <thead> <tr> </tr> </thead>
  <tbody>
    <tr>
      <td class="user-label">Name</td>
      <td> <%= @user.name %> </td>
    </tr>
    <tr>
      <td class="user-label">Role</td>
      <td> <%= @user.role_str %> </td>
    </tr>
    <tr>
      <td class="user-label">Email</td>
      <td> <%= @user.email %> </td>
    </tr>
  </tbody>
</table>
<%= link_to "Add skill", new_user_skill_path(@user), "data-role": "button" %>
<%= link_to "Edit Profile", edit_user_path(@user), "data-role": "button" %>
<% if @user.visitor? || @user.facilitator? %>
  <% if current_user.admin? %>
    <% if @user.facilitator? %>
      <%= form_tag disable_facilitator_path, method: 'post' %>
      <%= submit_tag "Disable facilitator" %>
    <% else %>
      <%= form_tag enable_facilitator_path, method: 'post' %>
      <%= submit_tag "Enable facilitator" %>
    <% end %>
  <% end %>
<% end %>

<% if @user.skills.any? %>
  <h2>Skills</h2>
  <table data-role="table" data-mode="reflow" class="ui-responsive table-stroke">
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @user.skills.each do |skill| %>
       <tr>
         <td> <%= skill.knowhow.name %> </td>
         <td>
           <% if skill.teaching %>
            Teaching
           <% else %>
            Learning
           <% end %>
         </td>
         <td>
           <%= form_tag user_skill_path(@user, skill), method: :delete do %>
            <%= submit_tag "Delete", data: { confirm: "Are you sure?"}, "data-theme": "b" %>
           <% end %>
         </td>
       </tr>
      <% end%>
    </tbody>
   </table>
<% end %>