config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/whatis'
  get 'static_pages/learners'
  get 'static_pages/teachers'
  get 'static_pages/organizers'
  get 'static_pages/contributors'
  get 'static_pages/media'

  root :to => 'groups#index'

  resources :users do
    resources :skills, only: [:new, :create, :destroy]
  end

  post 'users/:id/enable_facilitator', to: 'users#enable_facilitator', as: 'enable_facilitator'
  post 'users/:id/disable_facilitator', to: 'users#disable_facilitator', as: 'disable_facilitator'

  resource :login

  resources :groups do
    resources :events, only: [:create, :new, :edit, :update, :destroy, :show]
  end

  post 'groups/:group_id/events/:id/attend', to: 'events#attend', as: 'attend_event'
  post 'groups/:group_id/events/:id/unattend', to: 'events#unattend', as: 'unattend_event'

  post 'groups/:group_id/events/:id/agenda', to: 'events#agenda', as: 'create_agenda'

  get 'groups/:group_id/events/:id/visitors', to: 'events#visitors', as: "event_visitors"

  resources :locations, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<div class="error_messages">
  <ul>
    <% object.errors.full_messages.each do |msg_str| %>
      <li class="error_item"><%= msg_str %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<%= image_tag("banner_768x329.jpg", :alt => "learning meeting banner", id: "banner_img") %>

<div class="main-footer" data-role="footer" data-position="fixed">
  <h4>Thank you for using <a href="mailto:miljenko.jakovljevic@gmail.com">SkillPeer</a></h4>
</div>

app/views/shared/_header.html.erb
<div data-role="header" class="ui-header" role="banner">
  <h3><%= link_to "SkillPeer", root_path, "data-theme": "a" %></h3>
  <a href="" data-rel="back" class="ui-btn ui-icon-back ui-btn-icon-notext">Back</a>
  <%= link_to "Home", groups_path, {:class => "ui-btn ui-icon-home ui-btn-icon-notext"} %>
</div>

app/views/shared/_navbar.html.erb
<div data-role="navbar" data-mini="true">
  <ul>
    <% if ! logged_in?() %>
      <li><%= link_to "Groups", groups_path %></li>
      <li id="register"><%= link_to "Sign up", new_user_path %></li>
      <li><%= link_to "Login", new_login_path %></li>      
      <li><%= link_to "About", static_pages_home_path %></li>
    <% else %>
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <% if ! current_user.admin? %>
        <li><%= link_to "Groups", groups_path %></li>
      <% else %>
          <li><%= link_to "Users", users_path %></li>
      <% end %>
      <li id="logout_button"><%= button_to "Logout", login_path, {:action => "destroy", :method => "delete"} %></li>
      <li><%= link_to "About", static_pages_home_path %></li>
    <% end %>
  </ul>
</div>