config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/whatis'
  get 'static_pages/learners'
  get 'static_pages/teachers'
  get 'static_pages/organizers'
  get 'static_pages/contributors'
  get 'static_pages/media'

  root :to => 'groups#index'

  resources :users do
    resources :skills, only: [:new, :create, :destroy]
  end

  post 'users/:id/enable_facilitator', to: 'users#enable_facilitator', as: 'enable_facilitator'
  post 'users/:id/disable_facilitator', to: 'users#disable_facilitator', as: 'disable_facilitator'

  resource :login

  resources :groups do
    resources :events, only: [:create, :new, :edit, :update, :destroy, :show]
  end

  post 'groups/:group_id/events/:id/attend', to: 'events#attend', as: 'attend_event'
  post 'groups/:group_id/events/:id/unattend', to: 'events#unattend', as: 'unattend_event'

  post 'groups/:group_id/events/:id/agenda', to: 'events#agenda', as: 'create_agenda'

  get 'groups/:group_id/events/:id/visitors', to: 'events#visitors', as: "event_visitors"

  resources :locations, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  include ActiveModel::Validations

  belongs_to :group

  has_and_belongs_to_many :users

  validates :group_id, presence: true
  validates :time_start, presence: true
  validates :time_end, presence: true

  # DEBUG: Removed this validation for the time being since time_start and time_end apparently
  # have DateTime or TimeWithZone type
  #validates_format_of [:time_start, :time_end], with: /20\d\d-[01][1-9]-[0-3]\d [0-2]\d:[0-6]\d/

  validates_with EventTimeValidator

  def free_places?
    ((group.max_places - users.count) > 0)
  end

  def free_places
    group.max_places - users.count
  end

  def attending?(user)
    users.find_by(id: user.id)
  end

  def attend(user)
    self.users << user
  end

  # Gives the statistic of skills that are taught
  def teaching
    Knowhow.joins("JOIN skills, events_users ON knowhows.id=skills.knowhow_id \
    AND skills.teaching='t' AND skills.user_id=events_users.user_id \
    AND events_users.event_id=#{self.id}").group("knowhows.name").count
  end

  # Gives the statistic of skills that are learned
  def learning
    Knowhow.joins("JOIN skills, events_users ON knowhows.id=skills.knowhow_id \
    AND skills.teaching='f' AND skills.user_id=events_users.user_id \
    AND events_users.event_id=#{self.id}").group("knowhows.name").count
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  require 'agenda/manager'
  include Agenda

  before_action :user_is_facilitator,
  only: [:create, :destroy, :edit, :update, :agenda, :visitors]

  before_action :correct_facilitator,
    only: [:create, :destroy, :edit, :update, :show, :agenda, :visitors]

  before_action :correct_group,
    only: [:destroy, :edit, :update, :attend, :show, :agenda, :visitors]

  def new
    @group = Group.find(params[:group_id])
    @event = @group.events.new
  end

  def create
    @group = Group.find(params[:group_id])
    @event = @group.events.build(event_params)
    @event.validate
    if @event.valid?
      @event.save
      flash[:success] = "Meeting event created"
      redirect_to @group
    else
      flash.now[:danger] = "Meeting event not created"
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
    status = @event.update(event_params)
    if status
      flash[:success] = "Event update success"
      redirect_to group_path(@group)
    else
      flash.now[:danger] = "Event update failed"
      render 'edit'
    end
  end

  def show
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
    @learning_knowhows = @event.learning
    @teaching_knowhows = @event.teaching
    @visitors = []
    if group_facilitator?(@group, current_user)
      @visitors = @event.users
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    event = @group.events.find_by(id: params[:id])
    if event
      event.destroy
      flash[:success] = "Event deleted"
      redirect_to group_path(@group)
    else
      redirect_to root_url
    end
  end

  def attend
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
    if logged_in? && @event.free_places? && (! @event.attending?(current_user))
      @event.attend(current_user)
      flash[:success] = "Your name was added to the guest list."
      redirect_to group_event_path(@group, @event)
    else
      redirect_to root_url
    end
  end

  def unattend
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
    if @event && @event.attending?(current_user)
      @event.users.delete(current_user)
      flash[:success] = "Your name was removed from the guest list."
      redirect_to group_event_path(@group, @event)
    else
      redirect_to root_url
    end
  end

  def agenda
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
    if current_user && current_user.facilitator?
      manager = Manager.new(@group.area_size, @group.area_count)
      @event.users.each do |usr|
        manager.add_visitor(usr)
      end
      @agenda = manager.make_schedule
      if @agenda.empty?
        flash[:danger] = "Too few visitors, no agenda possible."
        redirect_to group_event_path(@group, @event)
      else
        render :agenda
      end
    end
  end

  def visitors
    @group = Group.find(params[:group_id])
    @event = @group.events.find_by(id: params[:id])
    @visitors = []
    if group_facilitator?(@group, current_user)
      @visitors = @event.users
    end
  end

  private

    def event_params
      params.require(:event).permit(:time_start, :time_end)
    end

    def group_facilitator?(group, user)
      user && group && user.facilitator? && group.facilitator_id == user.id
    end

    def correct_facilitator
      if current_user && current_user.facilitator?
        group = current_user.groups.find_by(id: params[:group_id])
        redirect_to root_url if group.nil?
      end
    end

    def user_is_facilitator
      unless current_user && current_user.facilitator?
        redirect_to root_url
      end
    end

    def correct_group
      gp = Group.find(params[:group_id])
      if gp.nil?
        redirect_to root_url
      else
        ev = gp.events.find_by(params[:id])
        if ev.nil?
          redirect_to root_url
        end
      end
    end

end#class EventsController

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<td>
  <%= object.time_start.strftime("%d %B %Y") %>
</td>
<td>
  <%= object.time_start.strftime("%H:%M") %>h
</td>
<td>
  <%= object.time_end.strftime("%H:%M") %>h
</td>
<td class="free_places">
  <%= @group.max_places - object.users.count %>
</td>
<td>
  <div class="command-toolbar">
    <div data-role="controlgroup" data-type="horizontal" data-mini="true">
      <%= button_to "Show", group_event_path(@group, object), {action: "show", method: "get", id: "event#{object.id}" } %>
    </div>
  </div>
</td>

app/views/events/_form.html.erb
<%= form_for [@group, @event] do |fb| %>
  <%= render "shared/error_messages", object: fb.object %>
  <div>
  <%= fb.label :time_start, "Start time" %>
  <%= fb.text_field(:time_start, class: "datetimepicker", id: "dtime_start") %>
  </div>
  <div>
  <%= fb.label :time_end, "End time" %>
  <%= fb.text_field :time_end, class: "datetimepicker", id: "dtime_end" %>
  </div>
  <%= fb.submit %>
<% end %>

app/views/events/agenda.erb
<h1> Event Agenda </h1>

<% if !@agenda.nil? and !@agenda.empty? %>

  <% agdArRd = @agenda.transpose %>

  <table data-role="table" data-mode="reflow" class="ui-responsive table-stroke">
    <thead>
      <tr>
        <th> Round </th>
        <% for idx in 0..(agdArRd[0].length - 1) %>
          <% if !agdArRd[0][idx].nil? %>
            <th> <%= idx + 1 %> </th>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
    <% area_idx = 1 %>
    <% agdArRd.each do |row| %>
      <% unless row[0].nil? %>
        <tr>
          <td class="area-name"> Area <%= area_idx %> </td>
          <% row.each do |trb| %>
            <% unless trb.nil? %>
              <% kwh = Knowhow.find(trb.knowhow_id) %>
              <td> <%= kwh.name %> </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
      <% area_idx += 1 %>
    <% end %>
  <tbody>
  </table>
<% end %>

app/views/events/edit.html.erb
<% provide :page_title, "Edit Page" %>

<h1> Edit Event </h1>

<%= render "form" %>

app/views/events/new.html.erb
<% provide :page_title, "New Event Page" %>

<h1>New Event</h1>

<%= render "form" %>

app/views/events/show.erb
<%# provide :page_title, "Event Page - #{@group.name}" %>

<h3><%= @group.name %></h3>
<h4><%= @event.time_start.strftime("%A, %d %B %Y") %></h4>
<h4><%= @event.time_start.strftime("%H:%M") %>h - <%= @event.time_end.strftime("%H:%M") %>h</h4>
<h4><%= @group.location.name %></h4>
<h4><%= @group.location.street %> <%= @group.location.number %></h4>
<h4><%= @group.location.postnr %> <%= @group.location.city %>, <%= @group.location.country %> </h4>
<h4>Places left: <%= @event.free_places %> </h4>

<% if current_user && current_user.facilitator? %>
  <div data-role="controlgroup" data-type="vertical">
    <%= link_to "Guest List", event_visitors_path(@group, @event), "data-role": "button" %>
    <%= button_to "Create Agenda", { action: "agenda", group_id: @group.id, id: @event.id} %>
  </div>
<% end %>

<div class="command-toolbar">
  <div data-role="controlgroup" data-type="horizontal" data-mini="true">
    <% if correct_facilitator?(@group) %>
      <%= button_to "Edit", edit_group_event_path(@group, @event),
          {action: "edit", method: "get", id: "edit_event#{@event.id}" }%>
      <%= form_tag group_event_path(@group, @event), method: 'delete' do %>
        <%= submit_tag "Delete", data: { confirm: "Are you sure you want to delete this event?" } %>
      <% end %>
    <% end %>
    <% if current_user && current_user.visitor? && !current_user.facilitator? %>

      <% unless attending?(@event) %>

        <%= form_tag attend_event_path(@group, @event), method: 'post' do %>
          <% if @event.free_places? %>
            <%= submit_tag "Interested" %>
          <% else %>
            <%= submit_tag "Interested", disabled: true %>
          <% end %>
        <% end %>

        <%= form_tag unattend_event_path(@group, @event), method: 'post' do %>
          <%= submit_tag "Not interested", disabled: true, class: "ui-btn-active ui-state-persist" %>
        <% end %>

      <% else %>

        <%= form_tag attend_event_path(@group, @event), method: 'post' do %>
          <%= submit_tag "Interested", disabled: true, class: "ui-btn-active ui-state-persist" %>
        <% end %>

        <%= form_tag unattend_event_path(@group, @event), method: 'post' do %>
          <%= submit_tag "Not interested" %>
        <% end %>

      <% end %>
    <% end %>
    <% if !logged_in? %>
      <%= link_to "Interested", new_login_path, "data-role": "button" %>
    <% end %>
  </div>
</div>

<h2>Skills Available</h2>

<% keys = (@learning_knowhows.keys + @teaching_knowhows.keys).uniq %>

<table id="event-skills" data-role="table" data-mode="reflow" class="ui-responsive table-stroke">
  <thead>
    <tr>
      <th> Skill </th>
      <th> Teaching </th>
      <th> Learning </th>
    </tr>
  </thead>
  <tbody>
    <% keys.each do |key| %>
      <tr>
        <td> <%= key %> </td>
        <td> <%= @teaching_knowhows[key] %> </td>
        <td> <%= @learning_knowhows[key] %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/visitors.erb
<% provide :page_title, "Lacotabo - Guest List" %>

<% unless @visitors.empty? %>
  <h2>Guest List</h2>
  <table data-role="table" data-mode="reflow" class="ui-responsive table-stroke">
    <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
      <% @visitors.each do |visitor| %>
        <tr>
          <td>
            <%= visitor.name %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>